'use client'

import { useState } from 'react'
import { Bot, RefreshCw, Sparkles } from 'lucide-react'

const BRIEFINGS = [
  [
    '3 infrastructure issues are expected to become Critical within the next 48 hours.',
    'Ward 4 shows the highest infrastructure decay trend this week.',
    'Heavy rainfall predicted — pothole severity likely to increase by ~18%.',
    'Recommended: Repair water leakage on SG Highway before rainfall begins.',
  ],
  [
    '2 RTI applications are due for filing within 72 hours.',
    'Streetlight failures are clustered in the north-west corridor — possible grid fault.',
    'Community verification activity is up 34% — citizen engagement is high.',
    'Recommended: Run Resolution Planner on the 3 oldest open issues.',
  ],
  [
    'Decay scores are rising fastest in the Garbage and Pothole categories.',
    'No new issues were resolved in the last 24 hours — escalation advised.',
    'Monsoon season impact: water leakage issues carry a 1.4× decay multiplier.',
    'Recommended: Trigger RTI for Issue #204 — 16 days unresolved, critical decay.',
  ],
]

function nowStr() {
  return new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })
}

export default function AIDailyBriefing({ critical, rtiCount }: { critical: number; rtiCount: number }) {
  const [idx, setIdx]           = useState(0)
  const [spinning, setSpinning] = useState(false)
  const [time, setTime]         = useState(nowStr)
  const confidence              = 87 + (idx * 3)

  const refresh = () => {
    setSpinning(true)
    setTimeout(() => {
      setIdx(v => (v + 1) % BRIEFINGS.length)
      setTime(nowStr())
      setSpinning(false)
    }, 700)
  }

  const bullets = BRIEFINGS[idx]

  return (
    <div className="p-5 bg-[#1C1C1C] border-b border-[#2E2E2E]">
      {/* Header */}
      <div className="flex items-start justify-between gap-3 mb-4">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-[#E8621A1A] border border-[#E8621A33] flex items-center justify-center shrink-0">
            <Bot size={15} className="text-[#E8621A]" />
          </div>
          <div>
            <p className="text-xs font-semibold text-white m-0">Gemini Daily Briefing</p>
            <p className="text-[9px] text-[#555] m-0 mt-0.5">Generated at {time} · {confidence}% confidence</p>
          </div>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <span className="text-[9px] bg-[#E8621A22] text-[#E8621A] border border-[#E8621A44] px-2 py-0.5 rounded">
            ✦ Generated by Gemini
          </span>
          <button
            onClick={refresh}
            disabled={spinning}
            className="w-7 h-7 flex items-center justify-center rounded border border-[#2E2E2E] bg-transparent text-[#555] hover:text-[#E8621A] hover:border-[#E8621A44] transition-colors cursor-pointer disabled:opacity-40"
            aria-label="Refresh briefing"
          >
            <RefreshCw size={12} className={spinning ? 'animate-spin' : ''} />
          </button>
        </div>
      </div>

      {/* Greeting */}
      <p className="text-sm text-[#888] mb-3 leading-relaxed">
        Good {new Date().getHours() < 12 ? 'morning' : new Date().getHours() < 17 ? 'afternoon' : 'evening'}.
        {' '}NEXORA analyzed today&apos;s civic data
        {critical > 0 ? ` — ${critical} critical issue${critical > 1 ? 's' : ''} require immediate attention` : ''}.
      </p>

      {/* Bullet points */}
      <ul className="flex flex-col gap-2 m-0 p-0 list-none mb-4">
        {bullets.map((b, i) => (
          <li key={i} className="flex items-start gap-2 text-xs text-[#888] leading-relaxed">
            <Sparkles size={11} className="text-[#E8621A] shrink-0 mt-0.5" />
            {b}
          </li>
        ))}
      </ul>

      {/* Confidence bar */}
      <div className="flex items-center gap-3">
        <span className="text-[9px] text-[#555] uppercase tracking-widest shrink-0">AI Confidence</span>
        <div className="flex-1 h-0.5 bg-[#2E2E2E] rounded-full">
          <div className="h-full rounded-full bg-[#E8621A] transition-all duration-700"
            style={{ width: `${confidence}%` }} />
        </div>
        <span className="text-[10px] text-[#E8621A] font-semibold shrink-0">{confidence}%</span>
      </div>
    </div>
  )
}
