import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { getCityFromCoords } from '@/lib/location'

export async function POST(request: NextRequest) {
  await new Promise(r => setTimeout(r, 1800))

  const { issue_id } = await request.json()
  const supabase = await createClient()

  const { data: issue } = await supabase.from('issues').select('*').eq('id', issue_id).single()
  if (!issue) return NextResponse.json({ error: 'Issue not found' }, { status: 404 })

  const { data: votes } = await supabase.from('votes').select('count').eq('issue_id', issue_id)
  const daysOld = Math.floor((Date.now() - new Date(issue.created_at).getTime()) / 86400000)
  const voteCount = (votes?.[0] as any)?.count ?? 0
  const today = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })

  // Get real city from coordinates
  const loc = await getCityFromCoords(issue.lat, issue.lng)
  const authority = issue.suggested_authority ?? loc.authority

  const draft = `RTI APPLICATION UNDER THE RIGHT TO INFORMATION ACT, 2005

Date: ${today}

To,
The Public Information Officer (PIO),
${authority},
${loc.display}.

Subject: Request for Information regarding unresolved civic issue — ${issue.title}

Respected Sir/Madam,

I, a citizen of ${loc.city}, hereby submit this application under the Right to Information Act, 2005 (Section 6) to seek information regarding a civic issue that has remained unresolved for ${daysOld} days despite being reported through the NEXORA Civic Intelligence Platform.

DETAILS OF THE ISSUE:
- Issue Title: ${issue.title}
- Category: ${issue.category.replace('_', ' ').toUpperCase()}
- Location: ${loc.display} (Coordinates: ${issue.lat?.toFixed(4)}, ${issue.lng?.toFixed(4)})
- Date of Original Report: ${new Date(issue.created_at).toLocaleDateString('en-IN')}
- Days Unresolved: ${daysOld} days
- Severity Level: ${issue.severity}/5
- Community Verifications: ${voteCount} citizens have independently verified this issue

DESCRIPTION:
${issue.description || issue.ai_summary || 'Civic issue reported by community members requiring immediate attention.'}

INFORMATION SOUGHT:
Under Section 6 of the RTI Act, 2005, I hereby request the following information:

1. What is the current status of this civic issue as on date?
2. What is the action plan for resolution of this issue with specific timelines?
3. What is the name, designation and contact details of the officer responsible for resolving this issue?
4. What is the budget allocated for the repair/resolution of this specific issue?
5. How many similar complaints have been received for this location in the past 12 months?
6. What is the standard operating procedure (SOP) for addressing this category of civic issue?

GROUNDS FOR URGENCY:
This issue has remained unresolved for ${daysOld} days and poses a significant risk to public safety and property. ${voteCount} community members have independently verified the existence and severity of this issue. The NEXORA Civic AI platform has assessed this issue with a high urgency decay score, indicating deteriorating conditions.

I request that the information be provided within 30 days as mandated under Section 7(1) of the RTI Act, 2005. In case of denial, please provide reasons as per Section 7(8) of the Act.

Thanking you,

Yours faithfully,
[Applicant Name]
[Contact Number]
[Email Address]
${loc.city}, ${loc.state}

---
This RTI application was auto-generated by NEXORA — Civic Intelligence Platform
Application Reference: RTI-NEXORA-${issue_id.slice(0, 8).toUpperCase()}
Generated on: ${today}`

  return NextResponse.json({ draft })
}